package org.smartrplace.apps.alarmingconfig.release;

public enum FinalAnalysis {

    PN101("PN101", "Netzwerk / Festnetz Kunde", "VPN-Verbindung auf Laptop möglich, aber nicht vom Controller"),
    PN120("PN120", "Netzwerk / Festnetz Kunde", "Gateway offline (Internetverbindung über Kundenanschluss)"),
    PN120_1("PN120.1", "Netzwerk / Festnetz Kunde", "Fehlkonfiguration oder Softwarefehler Smartrplace"),
    PN120_22("PN120.22", "Netzwerk / Festnetz Kunde", "Anschlüsse für LAN zum Kunden-Internet und zum Smartrplace-LAN vertauscht"),
    PN120_2("PN120.2", "Netzwerk / Festnetz Kunde", "Portsperrung o.ä. durch Kunden"),
    PN120_3("PN120.3", "Netzwerk / Festnetz Kunde", "Kunde trennt unser System Hardware-mäßig ohne Absprache"),
    PN130("PN130", "Netzwerk / Festnetz Kunde", "Gateway offline (Internetverbindung über Smartrplace-Mobilkarte)"),
    PN130_1("PN130.1", "Netzwerk / Festnetz Kunde", "Fehlkonfiguration oder Softwarefehler Smartrplace"),
    PN130_2("PN130.2", "Netzwerk / Festnetz Kunde", "Mobilempfang mit Telekom schlecht im Serverraum und angrenzenden Positionen, weitere Probleme Telekom"),
    PN130_3("PN130.3", "Netzwerk / Festnetz Kunde", "Kunde verändert Hardware-Verkabelung"),
    PN130_4("PN130.4", "Netzwerk / Festnetz Kunde", "Störung Mobilempfang"),
    PN140("PN140", "Netzwerk / Festnetz Kunde", "CCU verliert Verbindung"),
    PN140_1("PN140.1", "Netzwerk / Festnetz Kunde", "CCU hängt sich Hardware-mäßig auf"),
    PN140_2("PN140.2", "Netzwerk / Festnetz Kunde", "CCU wurde vom Kunden/Nutzer abgesteckt oder entfernt"),
    PN140_3("PN140.3", "Netzwerk / Festnetz Kunde", "Netzwerkverbindung wurde vom Kunden getrennt oder verändert"),
    PN140_32("PN140.32", "Netzwerk / Festnetz Kunde", "CCU erhält vom Gateway-DHCP-Server neue IP-Adresse"),
    PN140_33("PN140.33", "Netzwerk / Festnetz Kunde", "Konfiguration von Smartrplace-Seite fehlerhaft"),
    PN140_4("PN140.4", "Netzwerk / Festnetz Kunde", "CCU defekt"),
    PN140_5("PN140.5", "Netzwerk / Festnetz Kunde", "CCU bekommt bei nächtlichem Neustart wieder Kontakt"),
    PN142("PN142", "Netzwerk / Festnetz Kunde", "CCU startet nur noch im Recovery Modus"),
    PN145("PN145", "Netzwerk / Festnetz Kunde", "Controller verliert Verbindung"),
    PN145_1("PN145.1", "Netzwerk / Festnetz Kunde", "Controller hängt sich Hardware-mäßig auf"),
    PN145_2("PN145.2", "Netzwerk / Festnetz Kunde", "Controller wurde vom Kunden/Nutzer abgesteckt oder entfernt"),
    PN145_3("PN145.3", "Netzwerk / Festnetz Kunde", "Netzwerkverbindung wurde vom Kunden getrennt oder verändert"),
    PN145_4("PN145.4", "Netzwerk / Festnetz Kunde", "Controller defekt"),
    PN145_5("PN145.5", "Netzwerk / Festnetz Kunde", "Controller Settings waren zurückgesetzt"),
    PN145_6("PN145.6", "Netzwerk / Festnetz Kunde", "Nach Restart Treiber/Framework kommt Kontakt zurück"),
    PN150("PN150", "Netzwerk / Festnetz Kunde", "HAP verliert Verbindung"),
    PN150_1("PN150.1", "Netzwerk / Festnetz Kunde", "Durch Firmware-Update lösbar"),
    PN150_21("PN150.21", "Netzwerk / Festnetz Kunde", "Problem mit LAN-Verbindung kundenseitig"),
    PN150_22("PN150.22", "Netzwerk / Festnetz Kunde", "Problem mit LAN-Verbindung von Smartrplace"),
    PN150_3("PN150.3", "Netzwerk / Festnetz Kunde", "Keine Klärung, da HAP nicht benötigt wird"),
    PN150_4("PN150.4", "Netzwerk / Festnetz Kunde", "HAP über WLAN ohne stabilen Kontakt"),
    PN155("PN155", "Netzwerk / Festnetz Kunde", "HAP noch im Netzwerk erreichbar, aber nicht für CCU"),
    PN155_1("PN155.1", "Netzwerk / Festnetz Kunde", "CCU über WLAN mit Router verbunden"),
    PN155_2("PN155.2", "Netzwerk / Festnetz Kunde", "Anderes Problem"),
    PN160("PN160", "Netzwerk / Festnetz Kunde", "Airzone-Gerät verliert Kontakt"),
    PN160_1("PN160.1", "Netzwerk / Festnetz Kunde", "WLAN-Verbindung abgebrochen auf Grund von Abschaltung durch Kunden"),
    PN160_12("PN160.12", "Netzwerk / Festnetz Kunde", "WLAN-Verbindung abgebrochen durch Defekt/Problem Glinet-Router"),
    PN160_13("PN160.13", "Netzwerk / Festnetz Kunde", "Verbindung zum Gerät wird wieder aufgebaut nach Neustart OGEMA/Treiber"),
    PN160_2("PN160.2", "Netzwerk / Festnetz Kunde", "Airzone-Gerät defekt"),
    PN160_3("PN160.3", "Netzwerk / Festnetz Kunde", "Klimaanlage inkl. Airzone durch Kunden an Sicherung von Versorgung getrennt"),
    PN170("PN170", "Netzwerk / Festnetz Kunde", "Airzone-Gerät liefert keine plausiblen Temperatur-Messwerte, wenn ausgeschaltet"),
    PN310("PN310", "Software Development und Deployment", "Unerwartete Nebeneffekte Rollout eines Softwareupdates an viele/alle Gateways"),
    PN320("PN320", "Software Development und Deployment", "Problem beim Serverbetrieb"),
    PN320_1("PN320.1", "Software Development und Deployment", "Festplatte voll"),
    PN320_2("PN320.2", "Software Development und Deployment", "Störung beim Provider"),
    PN320_3("PN320.3", "Software Development und Deployment", "Prozess überlastet den Server"),
    PN330("PN330", "Software Development und Deployment", "Gateway startet nicht richtig auf (SmartrOS-Instanz instabil)"),
    PN330_1("PN330.1", "Software Development und Deployment", "SmartrOS startet immer wieder neu wegen Watchdog"),
    PN330_2("PN330.2", "Software Development und Deployment", "Fehlkonfiguration oder Softwarefehler Smartrplace z.B. Treiber"),
    PN410("PN410", "Software Development und Deployment", "Fehler Booking"),
    PN410_1("PN410.1", "Software Development und Deployment", "Software-Fehler"),
    PN410_2("PN410.2", "Software Development und Deployment", "Anwenderfehler"),
    PN410_3("PN410.3", "Software Development und Deployment", "Fehler in der Mandantenkonfiguration"),
    PN420("PN420", "Software Development und Deployment", "User-Synchronisation meldet \"Not authenticated\""),
    PN430("PN430", "Software Development und Deployment", "Fehler Roomcontrol"),
    PN430_1("PN430.1", "Software Development und Deployment", "Software-Fehler"),
    PN430_2("PN430.2", "Software Development und Deployment", "Fehlerhafte Konfiguration"),
    PN430_3("PN430.3", "Software Development und Deployment", "Anwenderfehler"),
    PN430_4("PN430.4", "Software Development und Deployment", "Veraltete Hardware"),
    PN440("PN440", "Software Development und Deployment", "Fehler SmartrOS"),
    PN450("PN450", "Software Development und Deployment", "Fehler Treiber/Cloud-Connection Konfiguration/Software"),
    PN450_1("PN450.1", "Software Development und Deployment", "Software-Fehler"),
    PN450_2("PN450.2", "Software Development und Deployment", "Konfigurationsfehler"),
    PN505("PN505", "Homematic Thermostate / Geräte", "Kompakt-Thermostate"),
    PN506("PN506", "Homematic Thermostate / Geräte", "CCU zeigt angelernte Geräte erst nach Neustart"),
    PN510("PN510", "Homematic Thermostate / Geräte", "Vor-Ort-Anlernen"),
    PN510_1("PN510.1", "Homematic Thermostate / Geräte", "CCU hat keine valide Verbindung zum Server"),
    PN510_2("PN510.2", "Homematic Thermostate / Geräte", "EMV-Störung behindert das Anlernen"),
    PN510_3("PN510.3", "Homematic Thermostate / Geräte", "Andere CCU lernt Thermostat an"),
    PN510_4("PN510.4", "Homematic Thermostate / Geräte", "CCU-Firmware nicht auf ausreichendem Stand"),
    PN530("PN530", "Weitere Geräte", "Gerät hat auf Netzwerkebene Kontakt, aber nicht in OGEMA/Treiber"),
    PN530_1("PN530.1", "Weitere Geräte", "Treiberneustart oder Framework-Neustart hilft"),
    PN530_2("PN530.2", "Weitere Geräte", "Treiber-Konfigurationsfehler"),
    PN530_3("PN530.3", "Weitere Geräte", "Treiber-Softwarefehler"),
    PN530_4("PN530.4", "Weitere Geräte", "Gerät falsch konfiguriert von Seiten Operation"),
    PN530_5("PN530.5", "Weitere Geräte", "Gerät falsch konfiguriert von Seiten Kunde"),
    PN530_6("PN530.6", "Weitere Geräte", "Unerwartetes Geräte-Verhalten erfordert Workaround"),
    PN605("PN605", "Weitere Geräte", "Thermostate senden regelmäßig unerwartete Setpoints, die nicht manuell gesetzt wurden / übernehmen Setpoints nicht"),
    PN605_1("PN605.1", "Weitere Geräte", "Plus-/Minus-Taste"),
    PN605_2("PN605.2", "Weitere Geräte", "Auto-Setpoint-Kurve wurde nicht korrekt an Thermostat übertragen"),
    PN605_22("PN605.22", "Weitere Geräte", "Auto-Mode nicht erfolgreich deaktiviert, obwohl bestätigt"),
    PN605_3("PN605.3", "Weitere Geräte", "Temperatursturzerkennung"),
    PN605_4("PN605.4", "Weitere Geräte", "Defekt Thermostat / Firmware"),
    PN605_5("PN605.5", "Weitere Geräte", "Verbleibende Direktkopplung mit Wandthermostat bei Dual-Heating/Cooling-Räumen"),
    PN605_6("PN605.6", "Weitere Geräte", "Übertragung Manu/Auto-Mode und Setpoints gestört durch EMV-Problem"),
    PN605_7("PN605.7", "Weitere Geräte", "Übertragung Setpoints nicht erfolgreich durch AdvancedRouting-Problem"),
    PN607("PN607", "Weitere Geräte", "Parameter werden nicht korrekt an Gerät übertragen"),
    PN607_1("PN607.1", "Weitere Geräte", "Übertragungsprobleme zwischen CCU und Gerät"),
    PN610("PN610", "Weitere Geräte", "Automatischer Modus wird erst noch einigen Stunden auf Thermostaten aktiviert"),
    PN620("PN620", "Weitere Geräte", "Thermostat vergessen zu installieren"),
    PN810("PN810", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Ventil öffnet nicht, auch wenn dies auf Grund von Setpoint und Measurement notwendig wäre"),
    PN640("PN640", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostate öffnen oder schließen nicht mehr richtig"),
    PN820("PN820", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "(zu besetzen)"),
    PN830("PN830", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Temperatur relativ hoch, auch wenn Ventil geschlossen ist"),
    PN830_1("PN830.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Weitere Wärmequelle im Raum"),
    PN830_2("PN830.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Heizkörper schließt generell nicht richtig"),
    PN830_3("PN830.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Ventil fährt nicht richtig zu (Problem Adaption)"),
    PN830_31("PN830.31", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Gelöst durch Einlegen einer Scheibe/Münze"),
    PN830_32("PN830.32", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat defekt durch Fremdeinwirkung"),
    PN830_33("PN830.33", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat gelockert durch Fremdeinwirkung"),
    PN830_34("PN830.34", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat gelockert da Kunststoffadapter"),
    PN830_35("PN830.35", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat-Tausch löst Problem, kein weiterer Grund erkennbar"),
    PN830_36("PN830.36", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Rücksetzen in den Werkzustand löst das Problem, kein weiterer Grund erkennbar"),
    PN830_4("PN830.4", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Hardware-Fehler des Thermostats"),
    PN830_5("PN830.5", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Problem mit der Firmware"),
    PN830_6("PN830.6", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Temperaturmessung defekt"),
    PN830_7("PN830.7", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat abgebaut vom Kunden"),
    PN831("PN831", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "F2-Fehler (ValveErrorState=6)"),
    PN831_1("PN831.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Arbeit am Ventil erforderlich"),
    PN831_2("PN831.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Lösung durch Entkalkungsfahrt"),
    PN832("PN832", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Bearbeitung: Thermostat schließt nicht richtig, weil Ventil nicht ausreichend zufährt"),
    PN840("PN840", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Heizkörper wird nicht warm, auch wenn Ventil geöffnet ist"),
    PN840_1("PN840.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Fenster im Raum geöffnet"),
    PN840_2("PN840.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Heizkörper nicht versorgt"),
    PN840_22("PN840.22", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Heizkörper muss entlüftet werden"),
    PN840_23("PN840.23", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Heizkörper ist verkalkt"),
    PN840_3("PN840.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Ventil fährt nicht richtig auf"),
    PN840_4("PN840.4", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Hardware-Fehler des Thermostats"),
    PN840_5("PN840.5", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Temperaturmessung defekt"),
    PN840_6("PN840.6", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Nachtabsenkung"),
    PN841("PN841", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "F1-Fehler (ValveErrorState=5)"),
    PN841_1("PN841.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Entkalkungsfahrt löst Problem"),
    PN841_2("PN841.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Weitere Analyse notwendig"),
    PN842("PN842", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Bearbeitung: Heizkörper wird nicht warm"),
    PN843("PN843", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Err-Fehler (ValveErrorState=0)"),
    PN843_1("PN843.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Durch Rücksetzen in den Werkzustand gelöst"),
    PN843_2("PN843.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Nicht durch Rücksetzen in den Werkzustand gelöst"),
    PN850("PN850", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat oder anderes Homematic-Gerät verliert Funkkontakt"),
    PN850_1("PN850.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Batterie leer"),
    PN850_2("PN850.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Funkreichweite nicht ausreichend"),
    PN850_22("PN850.22", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Funkreichweite nicht ausreichend mit Vermutung bekannter Hardware-Fehler"),
    PN850_23("PN850.23", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Gerät am AR-Limit"),
    PN850_3("PN850.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Batterien und/oder das Thermostat könnte vom Nutzer entfernt worden sein"),
    PN850_4("PN850.4", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Absturz Firmware"),
    PN850_5("PN850.5", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat defekt"),
    PN860("PN860", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat hat immer wieder Lücken über viele Stunden oder sogar Tage"),
    PN860_1("PN860.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Funkreichweite nicht ausreichend"),
    PN860_2("PN860.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "HAP wird z.B. über Zeitschaltuhr oder manuell aus- und angeschaltet"),
    PN860_3("PN860.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Funkstörer oder stark dämpfende Tür etc. ändern gelegentlich ihren Status"),
    PN860_4("PN860.4", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Bei Versorgung über Battery Pack wird Stromversorgung gelegentlich ausgeschaltet"),
    PN870("PN870", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Thermostat hat zu kurze Batterielaufzeit"),
    PN870_1("PN870.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Batterielaufzeit unerklärlich kurz"),
    PN870_2("PN870.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Batterielaufzeit kurz, aber erklärlich"),
    PN870_3("PN870.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Batterielaufzeit kurz nach Installationsphase"),
    PN880("PN880", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Ungültige Werte von Gerät geloggt"),
    PN880_1("PN880.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Gerät hat internen Fehler und sendet z.B. Fehlercode oder Sensor defekt"),
    PN880_2("PN880.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Treiber defekt"),
    PN885("PN885", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Einige Datenreihen von einem Gerät brechen plötzlich ab"),
    PN885_1("PN885.1", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Problem mit Gerät (Kundenkonfiguration)"),
    PN885_2("PN885.2", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Problem mit Gerät (Hardware-Defekt)"),
    PN885_3("PN885.3", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Problem mit Gerät (Konfiguration Smartrplace)"),
    PN885_4("PN885.4", "Heizkörper nicht kalt / nicht warm / F1/F2/F3-Fehler / Batterielaufzeit / Kontaktverlust", "Problem mit Treiber/Software"),
    PN210("PN210", "Gelöst und zu testen", "Keine Räume etc. angezeigt nach Einrichtung des Gateway");

    private final String code;
	private final String category;
	private final String description;
	
	private FinalAnalysis(String code, String category, String description) {
		this.code=code;
		this.category=category;
		this.description=description;
	}
	
	public String code() { 
		return code;
	}
	
	public String description() {
		return description;
	}
	
	public String category() {
		return category;
	}
	
	@Override
	public String toString() {
		return code+"-"+description;
	}

}