package org.smartrplace.smarteff.util.editgeneric;

import de.iwes.widgets.api.widgets.OgemaWidget;
import de.iwes.widgets.api.widgets.sessionmanagement.OgemaHttpRequest;

/**Provide widgets for the columns of the table*/
public interface EditLineProvider {
	/**If null use default widget generated by page*/
	default OgemaWidget labelColumn() {return null;}
	/**If null use default widget generated by page*/
	default OgemaWidget valueColumn() {return null;}
	/**If null use default widget generated by page*/
	default OgemaWidget linkColumn() {return null;}
	
	enum ColumnType {
		LABEL,
		VALUE,
		LINK
	}
	enum Visibility {
		HIDDEN,
		DISABLED,
		ENABLED
	}
	default Visibility visibility(ColumnType column, OgemaHttpRequest req) {return Visibility.ENABLED;}
}
