package org.smartrplace.extensionservice.gui;

import org.smartrplace.extenservice.resourcecreate.ExtensionCapabilityForCreate;
import org.smartrplace.extensionservice.ApplicationManagerSPExt;

/** A navigation page is an overview table or any other web page representation that allows to navigate
 * between views and that can initiate editing or creating of resources
 */
public interface NavigationGUIProvider extends ExtensionCapabilityForCreate {
	
	/** Initialize navigation page
	 * 
	 * @param page page with URL that was generated by main domain application
	 * @param generalData usually there is some data that does not depend on a parent that shall always be
	 * 		accessible. This information should be handed over here.
	 * @param appManMin
	 */
	void initPage(final ExtensionNavigationPageI<?, ?> page, ApplicationManagerSPExt appManExt);
	
	public enum PageType {
		EDIT_PAGE,
		TABLE_PAGE
	}
	PageType getPageType();
}