package org.smartrplace.extensionservice.gui;

import org.smartrplace.extensionservice.ApplicationManagerSPExt;
import org.smartrplace.extensionservice.resourcecreate.ExtensionCapabilityForCreate;

import de.iwes.widgets.api.widgets.navigation.MenuConfiguration;

/** Extension Capability for all kinds of visualization extensions, especially table navigation
 * pages and detail edit/value presentation pages for single resources
 */
public interface NavigationGUIProvider extends ExtensionCapabilityForCreate {
	
	/** Initialize navigation page
	 * 
	 * @param page page with URL that was generated by main domain application
	 * @param generalData usually there is some data that does not depend on a parent that shall always be
	 * 		accessible. This information should be handed over here.
	 * @param appManMin
	 */
	void initPage(final ExtensionNavigationPageI<?, ?> page, MenuConfiguration menuConfiguration,
			ApplicationManagerSPExt appManExt);
	
	public enum PageType {
		EDIT_PAGE,
		TABLE_PAGE
	}
	PageType getPageType();
}